version: '3'
services:
  initdb:
    build: ./initdb
    ports:
    - "8080:8080"
    networks:
    - tp
    depends_on:
    - bdd
  bdd:
    image: mongo
    ports:
    - "27027:27017"
    networks:
    - tp

networks:
  tp: